# Generated by Django 6.0.6 on 2026-06-30 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=210)),
                ('catalogue_type', models.CharField(choices=[('DCAT_RDF', 'DCAT RDF')], max_length=30)),
                ('harvest_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=30)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishing.publisher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('publisher_id', 'slug'), name='unique_publisher_slug')],
            },
        ),
    ]
