# Generated by Django 6.0.6 on 2026-06-30 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_harvestsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestsource',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
