# Generated by Django 6.0.6 on 2026-07-02 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('HARVESTING', 'Harvesting'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=30)),
                ('catalogue_result', models.TextField()),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishing.catalogue')),
            ],
        ),
    ]
