# Generated by Django 6.0.6 on 2026-07-02 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0003_harvestrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRunEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verb', models.CharField(max_length=50)),
                ('object', models.TextField()),
                ('target', models.TextField()),
                ('additional_context', models.TextField()),
                ('harvest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishing.harvestrun')),
            ],
        ),
    ]
