# Generated by Django 6.0.6 on 2026-07-02 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0004_harvestrunevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrun',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_run', to='publishing.catalogue'),
        ),
    ]
