# Generated by Django 6.0.6 on 2026-07-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0005_alter_harvestrun_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrunevent',
            name='verb',
            field=models.CharField(choices=[('CATALOGUE_VALIDATED', 'Catalogue marked valid'), ('CATALOGUE_INVALIDATED', 'Catalogue marked invalid'), ('LISTING_CATALOGUED', 'Listing catalogued'), ('LINK_CATALOGUED', 'Link catalogued'), ('LINK_VALIDATED', 'Link marked valid'), ('LINK_INVALIDATED', 'Link marked invalid'), ('LINK_ORPHANED', 'Link marked orphan')], max_length=50),
        ),
    ]
