# Generated by Django 6.0.6 on 2026-07-02 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0006_alter_harvestrunevent_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrunevent',
            name='harvest_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_event', to='publishing.harvestrun'),
        ),
    ]
