services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: python-run-dev
      args:
        INSTALL_DEV_DEPS: True
    image: datagovuk_local_django
    container_name: datagovuk_local_django
    volumes:
      - .:/app:z
      - /app/.venv
    env_file:
      - path: ./.envs/.local/.django
        required: false
    ports:
      - '8000:8000'
    command: /start
