services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: python-run-dev
      args:
        GIT_SHA: $GIT_SHA
    image: datagovuk_local_django
    container_name: datagovuk_local_django
    volumes:
      - .:/app:z
      - /app/.venv
    env_file:
      - path: ./.envs/.local/.django
        required: true
      - path: ./.envs/.local/.django-overrides
        required: false
    ports:
      - '8000:8000'
    depends_on:
      - db
    command: /start

  db:
    image: postgres:17-alpine
    container_name: datagovuk_local_db
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: datagovuk_local_redis
    ports:
      - "6379:6379"

  celery_worker:
    image: datagovuk_local_django
    container_name: datagovuk_local_celery_worker
    volumes:
      - .:/app:z
      - /app/.venv
    env_file:
      - path: ./.envs/.local/.django
        required: true
      - path: ./.envs/.local/.django-overrides
        required: false
    depends_on:
      - db
      - redis
    command: celery -A config.celery worker --loglevel=info

  playwright:
    build:
      context: ./docker/playwright
      dockerfile: ./Dockerfile
    image: datagovuk_local_playwright
    container_name: datagovuk_local_playwright
    ports:
      - '3000:3000'
