services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: python-run-dev
      args:
        GIT_SHA: $GIT_SHA
    image: datagovuk_local_django
    container_name: datagovuk_local_django
    volumes:
      - .:/app:z
      - /app/.venv
      # Mount host docker socket so testcontainers can talk to Docker
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - path: ./.envs/.local/.django
        required: true
      - path: ./.envs/.local/.django-overrides
        required: false
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    ports:
      - '8000:8000'
    command: /start
    depends_on:
      solr:
        condition: service_healthy

  playwright:
    build:
      context: ./docker/playwright
      dockerfile: ./Dockerfile
    image: datagovuk_local_playwright
    container_name: datagovuk_local_playwright
    ports:
      - '3000:3000'

  solr:
    image: ghcr.io/alphagov/solr:2.10
    platform: linux/amd64
    ports:
      - "8984:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data
    command: >
      bash -c "precreate-core ckan /opt/solr/server/solr/configsets/ckan;
               precreate-core ckan-test /opt/solr/server/solr/configsets/ckan; # Set up a ckan-test core with the same config for testing...
               exec solr -f"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/ckan/admin/ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  solr-data:
    build:
      context: ./docker/solr
      dockerfile: ./Dockerfile
    environment:
      SOLR_URL: "http://solr:8983/solr/ckan"
    depends_on:
      solr:
        condition: service_healthy
    command: ["python", "load_data.py"]

volumes:
  solr_data:
