# This file is for testing the production dockerfile using docker-compose -
# we will not use docker-compose in production
services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: python-run-production
    image: datagovuk_production_django
    container_name: datagovuk_production_django
    env_file:
      - path: ./.envs/.production/.django
        required: true
    ports:
      - '8001:8000'
    command: /start
