name: 'Setup Docker Stack'
description: 'Check out code, set up Buildx, build Bake cache, and start Docker Compose'
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4.3.0

    - name: Build and cache local backend
      uses: docker/bake-action@v7.3.0
      with:
        push: false
        load: true
        files: docker-compose.local.yml
        targets: django
        set: |
          django.cache-from=type=gha,scope=django-${{ github.ref_name }}
          django.cache-from=type=gha,scope=django-main
          django.cache-to=type=gha,scope=django-${{ github.ref_name }},mode=max

    - name: Bring up docker-compose stack
      shell: bash
      run: docker compose -f docker-compose.local.yml up -d
