name: Build and push datagovuk image on tags

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      buildType:
        description: Decide on what to build
        required: false
        type: string
      gitRef:
        description: Commit, tag or branch name to deploy
        required: false
        type: string

jobs:
  build_and_push:
    name: Build and push the datagovuk image w/ tags
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-image.yaml
    with:
      buildType: ${{ inputs.buildType || github.event.inputs.buildType || 'build_push_with_gittag' }}
      gitRef: ${{ inputs.gitRef || github.event.inputs.gitRef || github.ref_name }}
