name: Create deployment PRs on release tags creation

on:
  push:
    tags:
      - 'v*.*.*' # e.g. v1.2.3
    branches:
      - test-DGUK-565-update-trigger-for-workflow

jobs:
  tag_for_staging_production:
    name: Tag datagovuk image for staging and production
    uses: ./.github/workflows/tag-staging-production.yaml
    secrets: inherit

  create_deployment_prs:
    name: Create deployment PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # - run: bash ./docker/create-pr.sh
      - run: echo "job to create PR commented out atm"
    env:
      IS_TAG: "true"
      ENVS: "staging,production"
      GH_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}
      GH_REF: "v1.0.0-testing" # e.g. v1.2.3
