name: Create staging deployment PR on release tag

on:
  push:
    tags:
      - 'v*.*.*' # e.g. v1.2.3

permissions:
  contents: read
  packages: write

jobs:
  tag_for_staging_production:
    name: Tag datagovuk image for staging and production
    uses: ./.github/workflows/tag-staging-production.yaml
    secrets: inherit

  create_staging_deployment_pr:
    name: Create staging deployment PR
    needs: tag_for_staging_production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - run: bash ./docker/create-pr.sh
    env:
      IS_TAG: "true"
      ENVS: "staging"
      GH_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}
      GH_REF: ${{ github.ref_name }} # e.g. v1.2.3
