on:
  workflow_dispatch:
  workflow_call:

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack if failure on main
        uses: alphagov/govuk-infrastructure/.github/actions/report-run-failure@main
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: ${{ 'datagovuk-technical' }}
