on:
  push:
    branches:
      - test-DGUK-583-add-slack-notifications-cicd
  workflow_run:
    workflows:
      - Build and push multi-arch images
      - CI
      - CodeQL
      - Trivy Security Scan
      - Tag datagovuk image for staging and production
      - Create deployment PRs on release tags creation
      - Test slack notification with failure
      - Create integration PR
    types:
      - completed

jobs:
  notify-slack:
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.head_branch == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: Send test Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -sS -X POST \
            -H "Content-type: application/json" \
            --data '{"text":"Hello, this is a test notification"}' \
            "$SLACK_WEBHOOK_URL"