name: Tag datagovuk image for staging and production

on:
  workflow_dispatch:
  workflow_call:

jobs:
  smoke_tests:
    name: Run smoke tests on integration environment
    uses: ./.github/workflows/smoke-tests.yml
    secrets: inherit
    with:
      environment: "integration"
      expected_sha: ${{ github.sha }}

  tag_for_staging_production:
    name: Tag the image for use in staging and production
    needs: smoke_tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_REPO: ghcr.io/alphagov/datagovuk
      INTEGRATION_SHA: ${{ github.sha }}
      RELEASE_TAG: ${{ github.ref_name }} # e.g. v1.2.3
    steps:
      - name: fake run
        run: echo "this is a test"
