name: Test slack notification with failure

on:
  push:
    branches:
      - test-DGUK-583-add-slack-notifications-cicd

jobs:
    test-slack-notification:
        runs-on: ubuntu-latest
        steps:
            - name: Fail the workflow to test Slack notification
              run: exit 1
